---
latitude: 40.7174
longitude: -73.99585
map_zoom: 12
name: The SunBright
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 140 Hester Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10013'
_hotel_id: THE660
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
